---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
#Iimportamos los dataset de salud 
healthsystem <- read_csv("../dataset/healthsystem.csv")
healthsystem_ids <- read_csv("../dataset/healthsystem_ids.csv")
healthsystemgroup_ids <- read_csv("../dataset/healthsystemgroup_ids.csv")
comunas <- read_csv("../dataset/2017_06_27_comunas_datachile_fixed.csv")
```

```{r}
#Unificamos las id's en el dataset global 
temp1 <- merge(x = healthsystem, y = healthsystem_ids, by = "health_system_id")
temp2 <- merge(x = temp1 , y = comunas , by= "comuna_datachile_id")
#Eliminamos las columnas con las id's que no sirven 
sistema_salud <- temp2[,-c(1,2,12,14,15)]
#Eliminamos las variables del sistema 
remove(temp1, temp2, healthsystem, healthsystem_ids , healthsystemgroup_ids , comunas)
#Cambiamos el nombre de esta variable
sistema_salud[sistema_salud$health_system == 'Fuerzas Armadas, de Orden y Seguridad Pública',4] <- 'Fuerzas armadas'
```

```{r}
#Cambiamos el tipo de dato de ciertas columnas
sistema_salud$year = as.factor(sistema_salud$year)
sistema_salud$region_name = as.factor(sistema_salud$region_name)
sistema_salud$comuna_name = as.factor(sistema_salud$comuna_name)
sistema_salud$health_system = as.factor(sistema_salud$health_system)
head(sistema_salud)
```
**Análisis exploratorio**

```{r}
#Algunos datos
dim(sistema_salud) #La dimensión es de 1746044 x 11
sum(is.na(sistema_salud)) #No hay valores NA 
summary(sistema_salud)
```
```{r}
#Veamos la evolución de las distintas fonasas a lo largo de los años 
library(dplyr)
plan_salud <- sistema_salud[,c(1,4,9,10)]
plan_salud_ano <- plan_salud %>%
  group_by(plan_salud$year,plan_salud$health_system) %>%
  count() %>% 
  rename(ano = `plan_salud$year` , plan_de_salud = `plan_salud$health_system`)
head(plan_salud_ano)
```


```{r}
#Frecuancia relativa 
sum_2000 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2000'])
sum_2003 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2003'])
sum_2006 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2006'])
sum_2009 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2009'])
sum_2011 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2011'])
sum_2013 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2013'])
sum_2015 <-sum(plan_salud_ano$n[plan_salud_ano$ano=='2015'])
#Definimos una función para aplicarlo sobre las sumas 
relativa <- function(año,n){
  if(año == '2000'){
      return(n/sum_2000*100)
  }
  if(año == '2003'){
      return(n/sum_2003*100)
  } 
  if(año == '2006'){
      return(n/sum_2006*100)
  } 
  if(año == '2009'){
      return(n/sum_2009*100)
  } 
  if(año == '2011'){
      return(n/sum_2011*100)
  } 
  if(año == '2013'){
      return(n/sum_2013*100)
  } 
  if(año == '2015'){
      return(n/sum_2015*100)
  } 

}
plan_salud_ano$porcentaje <- mapply(relativa,plan_salud_ano$ano , plan_salud_ano$n)
head(plan_salud_ano)

```

```{r}
#Ahora ploteamos 
#un pequeño ajuste al año
plan_salud_ano$ano <- as.numeric(as.character(plan_salud_ano$ano))
#ahora ploteamos
library(ggplot2)
ggplot(data = plan_salud_ano , aes(x = ano , y = porcentaje , color = plan_de_salud)) + 
  geom_line() + 
  labs(title ="Análisis temporal del plan de salud", subtitle = "Encuesta Casen", x = "Año" , y= "Porcentaje de la población") + 
  scale_x_discrete(limits=c(2000, 2003, 2006,2009,2011,2013,2015))+
  ggsave("plan_salud_ano.png" , path = "../img/",width=10)
  
```
Vamos a graficar ahora el porcentaje de población que tiene isapre según las distintas comunas de chile

```{r}
comuna1 <- 'Quilicura'
comuna2 <- 'Puente Alto'
comuna3 <- 'Las Condes'
comuna4 <- 'Laja'
  
isapre <- sistema_salud[sistema_salud$health_system == 'Isapre',c(1,4,10,11)]
#veamos el caso particular de puente alto, quilicura y las condes 
isapre_comuna <- isapre %>%
  filter(comuna_name == comuna1 | comuna_name == comuna2 | comuna_name == comuna3 | comuna_name == comuna4) %>%
  group_by(year,comuna_name) %>%
  count()
#Este es el plan de todos los de esas comunas
todosplanes <- sistema_salud[,c(1,4,10,11)]
todosplanes_comuna <- todosplanes %>%
  filter(comuna_name == comuna1 | comuna_name == comuna2 | comuna_name == comuna3 | comuna_name == comuna4) %>%
  group_by(year,comuna_name) %>%
  count()

isapre_comuna$relativo <- isapre_comuna$n/todosplanes_comuna$n * 100

```

```{r}
#Ahora ploteamos 
#un pequeño ajuste al año
isapre_comuna$year <- as.numeric(as.character(isapre_comuna$year))
#ahora ploteamos
ggplot(data = isapre_comuna , aes(x = year , y = relativo , color = comuna_name)) + 
  geom_line() + 
  labs(title ="Análisis temporal del plan Isapre en algunas comunas", subtitle = "Encuesta Casen", x = "Año" , y= "Porcentaje de la población en la comuna con isapre") + 
  scale_x_discrete(limits=c(2000, 2003, 2006,2009,2011,2013,2015)) + 
  ggsave("plan_salud_ano_comunas.png" , path = "../img/",width=10)
  
```
```{r}
region1 <- 'Valparaíso'
region2 <- 'Región Metropolitana Santiago'
region3 <- 'Maule'
region4 <- 'Bío Bío'
  
#veamos el caso particular delas regiones metropolitana, valparaiso, biobio, maule 
isapre_region <- isapre %>%
  filter(region_name == region1 | region_name == region2 | region_name == region3 | region_name == region4) %>%
  group_by(year,region_name) %>%
  count()
#Este es el plan de todos los de esas comunas
todosplanes_region <- todosplanes %>%
  filter(region_name == region1 | region_name == region2 | region_name == region3 | region_name == region4) %>%
  group_by(year,region_name) %>%
  count()

isapre_region$relativo <- isapre_region$n/todosplanes_region$n * 100

```

```{r}
#Ahora ploteamos 
#un pequeño ajuste al año
isapre_region$year <- as.numeric(as.character(isapre_region$year))
#ahora ploteamos
ggplot(data = isapre_region , aes(x = year , y = relativo , color = region_name)) + 
  geom_line() + 
  labs(title ="Análisis temporal del plan Isapre en algunas regiones", subtitle = "Encuesta Casen", x = "Año" , y= "Porcentaje de la población en la region con isapre") + 
  scale_x_discrete(limits=c(2000, 2003, 2006,2009,2011,2013,2015)) + 
  ggsave("plan_salud_ano_region.png" , path = "../img/",width=10)
  
```
