---
title: "vivienda"
author: "cris"
date: "4/9/2021"
output: html_document
---
```{r}
#se abre datasets relevantes de vivienda
library(readr)
library(tidyverse)
household_for_db <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/household_for_db.csv")
zone_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/zone_id.csv")
water_source_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/water_source_id.csv")
land_using_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/land_using_id.csv")
comuna_ids <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/2017_06_27_comunas_datachile_fixed.csv")
walls_material_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/walls_material_id.csv")
less_than_20_blocks_health_center_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/less_than_20_blocks_health_center_id.csv")
less_than_20_blocks_educational_center_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/less_than_20_blocks_educational_center_id.csv")
less_than_8_blocks_public_transport_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/less_than_8_blocks_public_transport_id.csv")
paying_credit_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/paying_credit_id.csv")
household_sq_meters_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/household_sq_meters_id.csv")
water_distribution_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/water_distribution_id.csv")
subsidy_or_program_id <- read_csv("D:/OneDrive - Universidad de Chile/Primer Semestre 2021/Introducción a la Mineria de Datos/GitHub/fondaMinera/dataset/ids_household/subsidy_or_program_id.csv")
```


```{r}
household <- household_for_db #se crea copia del dataframe original
household$comuna_id <- comuna_ids$comuna_name[match(household$comuna_id,comuna_ids$comuna_customs_id)] #se reasignan las id de las comunas
household$comuna_datachile_id <- comuna_ids$region_name[match(household$comuna_id, comuna_ids$comuna_name)]
household$zone_id <- zone_id$value[match(household$zone_id, zone_id$id)] #se reasignan las ids de laz zonas con rural o urbano
household <- household[complete.cases(household$comuna_id), ] #se eliminan las entradas sin comuna
colnames(household)[colSums(is.na(household)) > 0] #se buscan los nombres de las columnas con NA
household <- household %>%
  rename(#se cambian los nombres de las columnas
    comuna_name = comuna_id,
    region_name = comuna_datachile_id,
    zone_type = zone_id
    ) %>%
  relocate(region_name) #se mueve region_name al principio

```
```{r}
#se cambian los NA con una id que representará 'Sin Dato'
household$family_member_owner[is.na(household$family_member_owner)] <- 3
household$family_member_owner_2[is.na(household$family_member_owner_2)] <- 9
household$subsidy_or_program[is.na(household$subsidy_or_program)] <- 5
household$credit[is.na(household$credit)] <- 7
household$paying_credit[is.na(household$paying_credit)] <- 5
household$reason_to_share[is.na(household$reason_to_share)] <- 9
```

```{r}
dim(household) #dimensiones del dataset a trabajar
sum(is.na(household)) #No hay valores NA 
household[,names(household)] <- lapply(household[,names(household)],factor) #se convierten a factor todas las col.
summary(household) #se obtiene un sumario
```

```{r}
unique(household$comuna_name) #nombres de las comunas con datos
unique(household$region_name) #nombres de las regiones con datos
colnames(household[-1:-3]) #nombre de los datos de las columnas
```
```{r}
ggplot(household[household$comuna_name %in% unique(household$comuna_name)[110:113],], aes(x = walls_material)) +
  geom_bar(fill = "white", colour = "black")+
  facet_grid(comuna_name ~ .) +
  coord_flip() +
  ylab('frecuencia') +
  scale_x_discrete('tipos', labels=walls_material_id$value) +
  ggtitle("Materiales de las paredes
          por comuna")
```
```{r}
ggplot(household[household$zone_type %in% unique(household$zone_type),], aes(x = walls_material)) +
  geom_bar(fill = "white", colour = "black")+
  facet_grid(zone_type ~ .) +
  coord_flip() +
  ylab('frecuencia') +
  scale_x_discrete('tipos', labels=walls_material_id$value) +
  ggtitle("Materiales de las paredes
          por tipo de zona")
```
```{r}
ggplot(household[household$region_name %in% unique(household$region_name)[11:13],], aes(x = walls_material)) +
  geom_bar(fill = "white", colour = "black")+
  facet_grid(region_name ~ .) +
  coord_flip() +
  ylab('frecuencia') +
  scale_x_discrete('tipos', labels=walls_material_id$value) +
  ggtitle("Materiales de las paredes
          por región")
```
```{r}
ggplot(household[household$zone_type %in% unique(household$zone_type),], aes(x = less_than_20_blocks_health_center)) +
  geom_bar(fill = "white", colour = "black")+
  facet_grid(zone_type ~ .) +
  coord_flip() +
  ylab('frecuencia') +
  scale_x_discrete('respuesta', labels=less_than_20_blocks_health_center_id$value) +
  ggtitle("Existencia de centro médico en menos de 20 cuadras")
```
```{r}
ggplot(household[household$region_name %in% unique(household$region_name)[12:15],], aes(x = subsidy_or_program)) +
  geom_bar(fill = "white", colour = "black")+
  facet_grid(region_name ~ .) +
  coord_flip() +
  ylab('frecuencia') +
  scale_x_discrete('tipo', labels=subsidy_or_program_id$value) +
  ggtitle("Tipo de subsidio o pograma
          por región")
```
```{r}
#comunas de santiago
comunas_stgo <- unique(household[household$region_name=='Región Metropolitana Santiago',]$comuna_name)
```
```{r}
#tabla que relaciona 2 atributos (en este caso paredes)
table(household$floor_material,household$walls_material, dnn=c('material del piso','material de las paredes'))
```



